language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "10.16.3"
notifications:
  email: false
stages:
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: lint
      name: eslint
      script: npm run lint
    - stage: lint
      name: commitlint
      before_script:
        - npm i -g @commitlint/travis-cli
      script: commitlint-travis
    - stage: test
      script: npm t
    - stage: deploy
      before_script:
        - npm i -g netlify-cli
      script:
        - npm run build
        - npx semantic-release
